# Generated by Django 4.1.6 on 2023-02-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=250)),
                ("password", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=250)),
                ("zipcode", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="stuff",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="Supp_phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
