# Generated by Django 4.1.6 on 2023-02-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default=0, upload_to="product"),
            preserve_default=False,
        ),
    ]
